f-person/git-blame.nvim

lua/gitblame/init.lua
On my neovim-0.4.4.0.git.15336.faa47eaff-1.fc33.x86_64 I could not use the plugin without exporting `check_file_in_git_repo`.
=> export check_file_in_git_repo

lua/gitblame/init.lua, plugin/gitblame.vim
Allow specifying the date format as in Lua's `os.date`.
I know, that only half-closes #7, but it is reasonable start (and also localizes at least the date format).
=> Configurable date format

lua/gitblame/init.lua, lua/gitblame/utils.lua, plugin/gitblame.vim
When project is managed by Repo like Android, user may open
Vim in the project root which contains many git repositories.
Old way can not handle this usage well.
Meanwhile, Using git command to detect git root is slow and
make code complex. In this patch, finddir is used instead of
git commit, which is fast enough to simplify code logic and
compatible with more directory organizations.
=> Enhance git root detection to support using in Repo

README.md, lua/gitblame/init.lua, lua/gitblame/utils.lua, plugin/gitblame.vim
Hi,
Not sure if this is something you want for the plugin but it's a feature I was after.
If I have an `NvimTree`, `SymbolsOutline`, or whatever other "not really a file" buffer open, each line shows the `Not Committed Yet` virtual text. It's not really a problem but it is a little annoying.
I figure it would be useful to be able to disable the virtual text by filetype.
=> Don't show blame info for configured filetypes

lua/gitblame/git.lua
Hi,
I like a lot `GitBlameOpenCommitURL` command, but it was not working for me because some remote urls have the SSH URL version, like: 
```
git@github.com:someorg/some-repo.git
ssh://git@gitlab-master.MyCompany.com:12051/Me/PROJECT1.git
git@gitlab-master.MyCompany.com:Me/PROJECT1.git
git@bitbucket.org:Me/PROJECT2.git
```
and also because of the `.git` word at the end, like:
`https://github.com/f-person/git-blame.nvim.git`
I figured it would be helpful if we normalize the remote url to support all formats
=> feat: Normalize remote url to use with GitBlameOpenCommitURL

lua/gitblame/init.lua
I am not really sure why this is happening. I sometimes get these undefined commits when doing git blame --contents -
I added the `-w` option and the commits show up
=> add -w options for git blame to avoid undefined commits

lua/gitblame/git.lua, lua/gitblame/init.lua, lua/gitblame/utils.lua
This escapes filepaths in the git commands and eliminates the usage of `get_posix_shell_command`, which required `sh` and `dirname` to be on the user path, allowing Windows users to use the plugin. It addresses issues #49 and #53.
The original `:GitBlameOpenCommitURL` also didn't work on Windows due to the `start` command not opening URLs when double quotes are present. Instead of deleting the quotes, I opted to do what `netrw#BrowseX()` (gx) does and use `url.dll` directly, which also allows the command to work on Windows if for some reason powershell or something else is the selected shell instead of cmd.
=> Windows shell compatability

lua/gitblame/init.lua, plugin/gitblame.vim
Instead of ignoring specific special filetypes, ignore all buffers with non-empty buftypes.
=> feat: Ignore special buffers

README.md, lua/gitblame/init.lua, plugin/gitblame.vim
Hi,
I just discover your plugin (an hour ago) and it's really awesome.
However, I saw that it's missing a feature that I liked in other blame plugins. So I added the feature for customizing the message
when a modification is not yet committed. 
By default, the message is ` Not Committed Yet` but now everyone can customize it.
I added how to do it in the README.md file.
> PS: this is my first ever open source contribution and I'm pretty excited 😁
=> feat: Add custom message when not committed yet

lua/gitblame/init.lua
Ensure `load_blames` is called when a command is called while the plugin is disabled. Allows commands like GitBlameCopySHA to work when the plugin is disabled.
Fixes regression of https://github.com/f-person/git-blame.nvim/issues/47.
=> [FIX] get_blame_info returns nil when files_data is nil

README.md, lua/gitblame/git.lua, lua/gitblame/init.lua, plugin/gitblame.vim
Providing these functionalities I used from GitLenses to this plugin, as they've been really helpful to me.
- Adds the command `GitBlameOpenFileURL` to open a browser tab with the currently open file (and line)
- Adds the command `GitBlameCopyFileURL` to copy the currently open file (and line) URL to the clipboard
=> feat: open file url

lua/gitblame/git.lua, lua/gitblame/utils.lua
This PR:
- Extracts the function `make_local_command` in `utils` module, to run a command in the current buffer file path
- Uses the above command when retrieving the current git branch
=> fix: git branch taking base vim pwd instead of current file path

lua/gitblame/git.lua
Hello! I noticed that bitbucket commit urls were giving me a "Resource not found" error when attempting to visit them in the browser.
The path for individual commits within bitbucket.org is `/commits/` instead of `/commit/` for bitbucket.org.
I've updated the relevant code here. Let me know what you think. Thanks!
=> Fix incorrect commit url for bitbucket repositories

README.md, lua/gitblame/init.lua, lua/gitblame/utils.lua, plugin/gitblame.vim
This feature allows the user to specify a column from which the blame message should start. If the line is longer than the specified column value for a given line it will use the default behavior (display at EOL) for that line.
=> feat: Add specify start column for blame message

lua/gitblame/init.lua
I've run into some errors after 7aed504.
The issue happens consistently when writing some characters in a new line at the bottom of a file and then exiting insert mode.
My changes guarantee that all fields which are substituted in format_blame_text (except the commit sha) are present for an uncommitted line.
I figured that the sha should be an empty string if it doesn't exist.
=> fix: Handle info sometimes being nil for uncommitted lines

README.md, lua/gitblame/git.lua, lua/gitblame/init.lua
The `GitBlameOpenFileURL` and `GitBlameCopyFileURL` commands construct file urls based on the remote url's current branch but disregard information that may have been committed since then, causing these commands to sometimes return the wrong line numbers. To fix this, I have modified these commands to use the latest commit SHA in the constructed file url. I believe this also fixes https://github.com/f-person/git-blame.nvim/issues/87.
=> feat: scope file urls to the latest commit

lua/gitblame/init.lua
This fixes a bug I introduced in https://github.com/f-person/git-blame.nvim/pull/94 :sweat: 
`HEAD` doesn't always equal `head` depending on how you clone a repo, but `HEAD` will always point to the checked out commit in the working directory. Whoops!
=> fix: use HEAD instead of head

lua/gitblame/git.lua, lua/gitblame/init.lua, plugin/gitblame.vim
After playing around a bit with `GitBlameOpenFileURL` and `GItBlameCopyFileURL` I thought it would be a great idea to add optional range functionality to the line selection. You would be able to select ranges of lines to reference, and many git repository hosting platforms support line ranges. If you execute one of these commands with a range (i.e. `:74,84GitBlameOpenFileURL`) or with a visual selection, the resulting URL will have the range highlighted ([here is an example range](https://github.com/f-person/git-blame.nvim/blob/02fadac1702c014ce49a9499137d798934bdb465/lua/gitblame/git.lua#L74-L84)). Otherwise, the existing behavior (selecting an individual line) will work as expected.
I tested in Github, Gitlab, and SourceHut repos (SourceHut uses a slightly different URL pattern).
=> feat: add optional range to file URLs

lua/gitblame/utils.lua
When using virtual_text_column=80 option, virtual text was placed on top of existing text and chars above 80 were removed.
This patch adds correct tab size to length of line.
=> fix: length of line was wrong when tabs were used for indentation

lua/gitblame/init.lua, plugin/gitblame.vim
Highlight link was set in gitblame.vim before parsing lua config which made lua config ineffective.
=> fix: Changing highlight_group from lua config does not work

README.md, lua/gitblame/init.lua
Based on the conversation in https://github.com/f-person/git-blame.nvim/issues/103, we have decided to open file URLs using the SHA of the blame commit rather than the most recent upstream commit to prevent 404s when the upstream is out of date. I accomplished this by modifying `get_blame_info` to accept a range of lines and fetch the most recent blame from the lines provided, and modifying `get_sha` to accept an optional range of lines. Then I removed `get_latest_sha`.
=> fix: Modify file URL commands to open relative latest commits

lua/gitblame/init.lua
Virtual text is still rendered when gitblame_display_virtual_text is 0
This bug occurs because nvim and vim treat 0 differently.
=> fix: Virtual text is still rendered when gitblame_display_virtual_text is 0

lua/gitblame/init.lua
I'm using lualine and when I run GitBlameDisable, the statusline still shows the text of the last time GitBlame was used
=> fix: reset current_blame_text when disable

lua/gitblame/init.lua
When setting `vim.g.gitblame_use_blame_commit_file_urls = true` and running the command `:GitBlameOpenCommitURL`, this error occurs:
```
E5108: Error executing lua: Vim:Error executing Lua callback: ...cal/share/nvim/lazy/git-blame.nvim/lua/gitblame/init.lua:559: attempt to call global 'get_sha' (a nil value)
stack traceback:
...cal/share/nvim/lazy/git-blame.nvim/lua/gitblame/init.lua:559: in function <...cal/share/nvim/lazy/git-blame.nvim/lua/gitblame/init.lua:547>
[C]: at 0x0102436920
stack traceback:
[C]: at 0x0102436920
```
`get_sha` is defined on `M`, so calling `M.get_sha` fixes this.
=> fix: get_sha incorrectly used as global function

lua/gitblame/init.lua
Vimscript and lua handle values a bit differently! This fixes https://github.com/f-person/git-blame.nvim/issues/113
Add this in your Vimscript config and verify that the plugin is disabled by default.
```vim
let g:gitblame_enabled = 0
```
=> fix: only enable gitblame when value is 1 or true

README.md, lua/gitblame/config.lua, lua/gitblame/init.lua, lua/gitblame/utils.lua
Recently, my main development environment was changed to windows. I found that the event used by git-blame is cursormoved, and this event is triggered very frequently.
Git itself on windows runs slower, which causes the entire neovim to be blocked
I replaced cursormoved with cursorhold
=> fix high cpu

lua/gitblame/git.lua, lua/gitblame/init.lua, lua/gitblame/utils.lua
While investigating https://github.com/f-person/git-blame.nvim/issues/117 I noticed that the urls generated by `GitBlameOpenCommitURL`, `GitBlameOpenFileURL`, `GitBlameCopyCommitURL`, and `GitBlameCopyFileURL` can sometimes have incorrect fallback values when used outside of a git repository. I fixed these commands so that the provide a reasonable fallback value or log to the command output.
Run the commands above and verify they provide a reasonable output for git repositories and other non-repository directories!
=> fix: add fallbacks for url commands

lua/gitblame/init.lua
There is a bug currently where if `current_blame_text` is `nil` (which it will be if you are _not_ in a git repo), `is_blame_available` will return true and you will get `nil` displayed in your statusline.
This fixes that by adding a check for if not nil as well as not an empty string.
=> Fixes bug with nil current_blame_text

lua/gitblame/git.lua
Hi,
As we've discussed in #117, the URLs produced by the plugin's command aren't compatible with Azure since Azure uses different format than other git providers.
This PR adds support for Azure repos, let me know what you think about it.
=> feat: add support for azure repos

lua/gitblame/init.lua, lua/gitblame/utils.lua
The PR #121 introduced some side-effects which made the plugin feel more laggy overall because of how the virtual text got cleared with a delay. This commit retains the original delay behavior for displaying, while immediately clearing the virtual text on cursor move.
Previous behavior: 
https://github.com/f-person/git-blame.nvim/assets/31893391/59f68069-7741-4af3-9857-c130f1c5877b
Current behavior:
https://github.com/f-person/git-blame.nvim/assets/31893391/49c8e320-8e63-480d-bf44-c5a70c725f7b
@bossley9 this doesn't yet switch the default to 0 since it's probably good to 1) reconsider doing that after this change (i would probably still be in favor of that), 2) nicer to do in a separate PR
=> fix: Clear virtual text immediately on cursor move

README.md, lua/gitblame/config.lua, lua/gitblame/init.lua, lua/gitblame/utils.lua
First off, thanks for this! I've been using it for a while and it's really useful :)
I have a (somewhat) weird setup, where I use neovim over SSH with X11 forwarding (with XQuartz on my macOS host) so that I can share my clipboard, and hence the `:GitblameCopy..` commands don't work for me unless I apply a patch to use another clipboard register.
Another option here would be to use the vim option as opposed to hardcoded "+", such as `vim.opt.clipboard`. I'm happy to change to that too. (I made a PR using that approach here: https://github.com/f-person/git-blame.nvim/pull/137)
=> config: allow configure custom clipboard register

README.md, lua/gitblame/config.lua, lua/gitblame/init.lua, lua/gitblame/utils.lua
Solves issue #139 
"It would be nice if the description part of the blame could be configured to only show the first n characters for a more consistent output length."
=> feat: configurable commit summary length
